name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build the application
        run: npm run build

      - name: List files in dist directory
        run: ls -la ./dist

      - name: Archive build folder
        run: tar -czf build.tar.gz -C dist .

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build.tar.gz

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: build

      - name: List files in dist directory
        run: tar -tzf build.tar.gz

      - name: Deploy to server
        uses: appleboy/scp-action@v0.1.1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: "build.tar.gz"
          target: "/var/www/siriusServiceDesk/"

      - name: Extract build on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            tar -xzf /var/www/siriusServiceDesk/build.tar.gz -C /var/www/siriusServiceDesk
            rm /var/www/siriusServiceDesk/build.tar.gz
            service nginx restart
